<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>CD</AssemblyName>
    <RootNamespace>CD.Windows</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Engine\cdx.exe" Condition="Exists('Engine\cdx.exe')" CopyToOutputDirectory="PreserveNewest" Link="cdx.exe" />
  </ItemGroup>
</Project>
